import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UWHU Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">UWHU Kit</a>
        </h1>

        <p className={styles.description}>
          Get started With the <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">UWHU Kit</a>
          
        </p>

        <div className={styles.grid}>
          <a href="./match/mainMatch" className={styles.card}>
            <h2>Feuille de Match &rarr;</h2>
            <p>Application de numérisation de feuille de match de hockey subaquatique dit aussi sous l'eau</p>
          </a>

          <a href="./match/testCanva" className={styles.card}>
            <h2>Test F2M</h2>
            <p>Ici ça test la feuille match mon gars</p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
} 