import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
const axios = require('axios').default
export default function Home({dataPlayer}) {


  function resetDb(list){
    list.map(player => {
      axios.put('http://127.0.0.1:3000/api/apiPlayer',{
    
            params:{
                id : player.id,
                goal: 0
            }}).catch(console.log(`reset but à ${player.name} ${player.surname}sur la db`))
    
    })
  }





  return (
    <div className={styles.container}>
      <Head>
        <title>UWHU Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button type="button" class="btn btn-warning btn-lg btn-block" onClick={() =>{resetDb(dataPlayer);}}>Warning</button>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">UWHU Kit</a>
        </h1>

        <p className={styles.description}>
          Get started With the <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">UWHU Kit</a>
          
        </p>

        <div className={styles.grid}>
          <a href="./match/mainMatch" className={styles.card}>
            <h2>Feuille de Match &rarr;</h2>
            <p>Application de numérisation de feuille de match de hockey subaquatique dit aussi sous l'eau</p>
          </a>

          
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
} 

export async function getStaticProps(){
    

  const dataPlayerReq = await axios.get('http://127.0.0.1:3000/api/apiPlayer')

  const [dataPlayer] = await Promise.all([dataPlayerReq])
  
  return {
      props : {
          dataPlayer : dataPlayer.data
      }
  };
};